#!/bin/bash
# GENERATED by generate-ventz-mods.sh on 2026-08-06 — do not edit by hand.
#
# Re-applies the Ventz overlay after a PaperMod upgrade (or onto a fresh site).
# Snapshot base: PaperMod d376885 (2026-08-02), Hugo v0.164.0+extended+withdeploy.
#
# Run from the SITE ROOT, with the theme submodule already updated:
#   ./ventz-mods/reapply.sh
#
# Site-only files are copied verbatim. Theme overrides are resolved by a real
# 3-way merge (git merge-file):
#     base   = ventz-mods/base/<f>   the theme file this overlay was built on
#     ours   = ventz-mods/<f>        the customized version
#     theirs = themes/PaperMod/<f>   the NEW upstream version
# Non-overlapping upstream changes merge silently; overlapping ones land as
# <<<<<<< conflict markers. (BSD patch on macOS has no --merge, hence git.)
set -uo pipefail
cd "$(dirname "$0")/.."
mods="ventz-mods"
theme="themes/PaperMod"
fail=0

# Safety: never silently clobber a site-only file that has drifted from the
# snapshot (e.g. hugo.yaml edited since the last generate). FORCE=1 overrides.
copy_site_only() {   # $1 = site-relative path
    local f="$1"
    if [ -f "$f" ] && ! /usr/bin/diff -q "$mods/$f" "$f" >/dev/null 2>&1 && [ "${FORCE:-0}" != "1" ]; then
        echo "    SKIPPED  : $f differs from the snapshot — re-run with FORCE=1 to overwrite"; fail=1; return
    fi
    mkdir -p "$(dirname "$f")"; /bin/cp -f "$mods/$f" "$f"
}

echo '> Copying site-only files'
copy_site_only layouts/about.html
copy_site_only layouts/pages.html
copy_site_only assets/css/extended/ventz-a11y.css
copy_site_only assets/css/extended/ventz-entry-preview.css
copy_site_only assets/css/extended/ventz-search.css
copy_site_only static/_headers
copy_site_only static/android-chrome-192x192.png
copy_site_only static/android-chrome-512x512.png
copy_site_only static/apple-touch-icon.png
copy_site_only static/bsd_logo.png
copy_site_only static/favicon-16x16.png
copy_site_only static/favicon-32x32.png
copy_site_only static/favicon.ico
copy_site_only static/js/wordcloud2.js
copy_site_only static/site.webmanifest
copy_site_only archetypes/default.md
copy_site_only archetypes/posts.md
copy_site_only hugo.yaml

merge_override() {   # $1 = site-relative path
    local f="$1"
    if [ ! -f "$theme/$f" ]; then
        echo "    GONE     : $f no longer exists in the theme — snapshot copy used verbatim"
        mkdir -p "$(dirname "$f")"; /bin/cp -f "$mods/$f" "$f"; fail=1; return
    fi
    mkdir -p "$(dirname "$f")"
    /bin/cp -f "$mods/$f" "$f"          # ours -> working file, merged in place
    if git merge-file \
            -L "Ventz overlay" -L "PaperMod base (d376885)" -L "PaperMod (new)" \
            "$f" "$mods/base/$f" "$theme/$f"; then
        if /usr/bin/diff -q "$mods/$f" "$f" >/dev/null 2>&1; then
            echo "    ok       : $f (upstream unchanged here)"
        else
            echo "    merged   : $f (upstream changes folded in cleanly)"
        fi
    else
        echo "    CONFLICT : $f  <-- resolve the <<<<<<< markers, keep the Ventz Changes intent"; fail=1
    fi
}

echo '> Re-applying theme overrides (3-way merge)'
merge_override layouts/_markup/render-image.html
merge_override layouts/_partials/comments.html
merge_override layouts/_partials/extend_footer.html
merge_override layouts/_partials/footer.html
merge_override layouts/_partials/header.html
merge_override layouts/_partials/templates/opengraph.html
merge_override layouts/baseof.html
merge_override layouts/index.json
merge_override layouts/list.html
merge_override layouts/rss.xml
merge_override layouts/taxonomy.html
merge_override assets/css/common/header.css
merge_override assets/css/common/md-content.css
merge_override assets/css/common/post-entry.css
merge_override assets/css/common/post-single.css
merge_override assets/css/core/reset.css
merge_override assets/css/core/theme-vars.css
merge_override assets/js/fastsearch.js

echo ''
if [ $fail -eq 0 ]; then
    echo '🎉 Overlay re-applied cleanly. Rebuild: hugo server -D --disableFastRender'
else
    echo '⚠ Re-applied with conflicts — resolve them, then run ./generate-ventz-mods.sh'
fi
exit $fail
